export const FETCH_COLLECTION = "FETCH_COLLECTION";
export const FETCH_COLLECTION_FULFILLED = "FETCH_COLLECTION_FULFILLED";

export const FETCH_SHOW = "FETCH_SHOW";
export const FETCH_SHOW_FULFILLED = "FETCH_SHOW_FULFILLED";

export const FETCH_SHOW_SEASON = "FETCH_SHOW_SEASON";
export const FETCH_SHOW_SEASON_FULFILLED = "FETCH_SHOW_SEASON_FULFILLED";

export const SET_FAVORITE_SHOW = "SET_FAVORITE_SHOW"
export const FETCH_FAVORITE_SHOWS = "FETCH_FAVORITE_SHOWS"
export const FETCH_FAVORITE_SHOWS_FULFILLED = "FETCH_FAVORITE_SHOWS_FULFILLED"